### ISSUE TITLE
Request for proposal to merge to aiohttp

### ISSUE THREAD

**Issue by WisdomPill** [inyutin/aiohttp_retry#16]
Hello @inyutin,

I was looking for a way to configure session level retries like `requests` does and I came across this library.

My question is, have you ever considered proposing this method for retries to the people from `aiohttp`?

So people will find it more easily and use it out of the box, 
and of course being part of `aiohttp` it will be tested against every change of the codebase.

Best regards, Anas

**Comment by inyutin** [comment]
Hi @WisdomPill !
 
Can you, please, show me an example of using retries in ```request``` library? Unfortunately, I have very basic experience with it, so I don't truly understand what do you mean.

**Comment by WisdomPill** [comment]
[here](https://www.peterbe.com/plog/best-practice-with-retries-with-requests) you can find a way of doing retries with `request`.  Your approach seems similar, my question is if you have proposed to the `aiohttp` team your approach to perform retries like your library does

**Comment by inyutin** [comment]
I see, thank you.

See discussion here: https://github.com/aio-libs/aiohttp/issues/3133
It was quite along time ago, but I suppose we can suggest that aiohttp maintainers don't want to add retry to aiohttp itselt, but don't mid if it will be standalone solution.  

They probably should know about my solution, because I added it in third party aiohttp related libs list. See: https://github.com/aio-libs/aiohttp/pull/5296. However, they didn't add any additional commentaries.

**Comment by WisdomPill** [comment]
Okay, thanks for the information, what a shame, it would have been nice to have retries built in
