### ISSUE TITLE
Log retry attempts

### ISSUE THREAD

**Issue by renecouto** [inyutin/aiohttp_retry#3]
I think it would be useful if the request attempt number was logged, at least in debug mode

**Comment by inyutin** [comment]
Thank you for your suggestion! 

I'm added debug log for attempt number in v.1.1. Due to https://github.com/inyutin/aiohttp_retry/issues/7 aiohttp_retry==1.2 should be fine.

However, if you're planning to update I recommend v2.0. It is not compatible with previous versions, but it makes easier to specify all those retry options.  You can find out new examples at [Readme.md].(https://github.com/inyutin/aiohttp_retry#examples-of-usage)

I'm sorry for such a long time not responding.
