### ISSUE TITLE
Do not use list as function arguments

### ISSUE THREAD

**Issue by kamyar1979** [inyutin/aiohttp_retry#31]
Using mutable types (like list) for functions is not a good practice. Please try to use tuple (immutable) or iterable (even better).

**Comment by inyutin** [comment]
I see no problem with passing argument as list in this case. Yes, list is mutable, however it obviously wouldn't change during execution. The thing is: if user pass list to your library, you should be carefully about changing it. And you can see that's why I copy it before extending:
https://github.com/inyutin/aiohttp_retry/blob/master/aiohttp_retry/__init__.py#L374

I don't want to use iterable, because it doesn't guarantee stable iterable order. Moreover, dict is iterable too, but it can't be used the same way as list of urls. 

But using tuple seems good. So I would allow pass urls as tuple of urls too.

**Comment by inyutin** [comment]
I just released v2.3.5, where tuple of str is allow as url argument. However, you still can use list. If you have arguments why this behaviour is bad - please, let's discuss.

**Comment by kamyar1979** [comment]
In any programming language, sending reference to mutable arguments is BAD! If you consider Python built-in packages, most of them use iterables and some use tuple. You can study about immutability and side effects for better understanding. Do not use mutable types as function parameters. They use reference to dynamic memory which makes code slower and causes memory leak either. List is used just when you want to resize it and add/remove items.

**Comment by inyutin** [comment]
@kamyar1979 I refactored code so tuple of urls is passed to ```RequestContext```. However, I certainly don't want to forbid passing list of urls by type annotation. Type annotation is still: ```Union[StrOrURL, List[StrOrURL], Tuple[StrOrURL, ...]]```
