### ISSUE TITLE
Default retry on connection error

### ISSUE THREAD

**Issue by miro-balaz** [inyutin/aiohttp_retry#35]
It would be nice if  it was easy to set it up for handling also connection errors. Either by including aiohttp.ClientConnectionError or aiohttp.ServerConnectionError as default values, or expose them through global variable/function.
Thanks

**Comment by inyutin** [comment]
@miro-balaz thank you for your suggestion, but i'm quite unsure about this one. I don't want to include any exceptions as defaults, because it's quite hard to understand which exceptions are the most common one.

Can you, please, provide an example how would you like to use grobal variable/function?

I suggest, you can, in your own code, use something like this:

```python
class RetryConnectionErrors(RetryClient):
    def __init__(
        self,
        logger: Optional[_Logger] = None,
        retry_options: RetryOptionsBase = ExponentialRetry(),
        raise_for_status: bool = False,
        *args: Any, **kwargs: Any,
    ):
        retry_options_exceptions = set(retry_options.exceptions)
        retry_options_exceptions.update({ClientConnectionError, ServerConnectionError})
        
        retry_options_copy = copy.deepcopy(retry_options)
        retry_options_copy.exceptions = retry_options_exceptions
        
        super(RetryConnectionErrors, self).__init__(logger, retry_options, raise_for_status, *args, **kwargs)
```

Then, you can use ```RetryConnectionErrors``` instead ```RetryClient```.

However, I don't feel it is necessary to include such an alias to library.

**Comment by inyutin** [comment]
I close this issue, for now, but, please, will free to re-open it, if you have something to add.
